name: fetch_version

on:
  schedule:
    - cron: "0 15 * * *" # なんとなく15時に実行

jobs:
  fetch:
    runs-on: ubuntu-latest
    container: ryutah/lang-tool-versions
    steps:
      - uses: actions/checkout@v2
      - name: fetch versions
        run: |
          lang-tool-versions
      - name: upload versions file
        uses: actions/upload-artifact@v1
        with:
          name: versions
          path: versions.json

  push_changes:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
      - uses: actions/checkout@v2
      - name: download versions file
        uses: actions/download-artifact@master
        with:
          name: versions
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if [[ ! -z $(git --no-pager diff --cached --name-only --diff-filter=ACMRTUX) ]]; then
            git commit -m "chore: update versions"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
